server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name:
    url: jdbc:postgresql://localhost:5432/orders
    username: admin
    password: rt53jn
  jpa:
    database-platform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
